const users = [
  {
    name: 'Omar Elsayed',
    email: 'omar.elsayed@example.com',
    password: 'TestPass123',
    passwordConfirm: 'TestPass123',
    role: 'user',
  },
  {
    name: 'Laila Ahmed',
    email: 'laila.ahmed@example.com',
    password: 'SecurePass456',
    passwordConfirm: 'SecurePass456',
    role: 'user',
  },
  {
    name: 'Youssef Gamal',
    email: 'youssef.gamal@example.com',
    password: 'Password789',
    passwordConfirm: 'Password789',
    role: 'admin',
  },
  {
    name: 'Sara Nabil',
    email: 'sara.nabil@example.com',
    password: 'MyPass1234',
    passwordConfirm: 'MyPass1234',
    role: 'user',
  },
  {
    name: 'Mohamed Adel',
    email: 'mohamed.adel@example.com',
    password: 'AdelPass987',
    passwordConfirm: 'AdelPass987',
    role: 'admin',
  },
  {
    name: 'Nour Hassan',
    email: 'nour.hassan@example.com',
    password: 'NourPass321',
    passwordConfirm: 'NourPass321',
    role: 'user',
  },
  {
    name: 'Karim Mostafa',
    email: 'karim.mostafa@example.com',
    password: 'KarimSecure1',
    passwordConfirm: 'KarimSecure1',
    role: 'user',
  },
  {
    name: 'Heba Ibrahim',
    email: 'heba.ibrahim@example.com',
    password: 'HebaPass543',
    passwordConfirm: 'HebaPass543',
    role: 'user',
  },
  {
    name: 'Ali Tarek',
    email: 'ali.tarek@example.com',
    password: 'AliStrong999',
    passwordConfirm: 'AliStrong999',
    role: 'admin',
  },
  {
    name: 'Dina Osama',
    email: 'dina.osama@example.com',
    password: 'DinaTest111',
    passwordConfirm: 'DinaTest111',
    role: 'user',
  },
  {
    name: 'Rana Fathy',
    email: 'rana.fathy@example.com',
    password: 'RanaSecure789',
    passwordConfirm: 'RanaSecure789',
    role: 'user',
  },
  {
    name: 'Ahmed Nabil',
    email: 'ahmed.nabil@example.com',
    password: 'NabilTest2024',
    passwordConfirm: 'NabilTest2024',
    role: 'user',
  },
];
